name: Terrascan
on: [push]

jobs:
  terrascan_job_terradorm:
    runs-on: ubuntu-latest
    permissions:
        security-events: write
    name: terrascan-terraform
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'all'
        only_warn: true
        sarif_upload: true

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: terrascan.sarif

  terrascan_job_k8s:
    runs-on: ubuntu-latest
    permissions:
        security-events: write
    name: terrascan-k8s
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'k8s'
        iac_version: 'v1'
        policy_type: 'all'
        only_warn: true
        sarif_upload: true

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: terrascan.sarif