apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: dragonfly-operator-system
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
  targetNamespace: dragonfly-operator-system
  values:
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: true
