---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriametrics
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    uid: VictoriaMetrics
    name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://vmsingle-vm:8428
    isDefault: true
    jsonData:
      tlsSkipVerify: true
      timeInterval: 5s
