---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriametrics
  namespace: monitoring
spec:
  resyncPeriod: 10m
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    uid: VictoriaMetrics
    name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://vmsingle-vm:8428
    isDefault: true
    jsonData:
      tlsSkipVerify: true
      timeInterval: 5s
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victorialogs
  namespace: monitoring
spec:
  resyncPeriod: 10m
  instanceSelector:
    matchLabels:
      dashboards: grafana
  plugins:
  - name: victoriametrics-logs-datasource
    version: 0.27.1
  datasource:
    uid: VictoriaLogs
    name: VictoriaLogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://vlsingle-main.logging.svc.cluster.local:9428
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriatraces
  namespace: monitoring
spec:
  resyncPeriod: 10m
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    uid: VictoriaTraces
    name: VictoriaTraces
    type: jaeger
    access: proxy
    url: http://vtsingle-main.tracing.svc.cluster.local:10428/select/jaeger
