{{- if .Values.persistentConfig.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: radarr-config
spec:
  resources:
    requests:
      storage: 200
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
{{- end }}