apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-ui
  namespace: vault
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - match: Host(`vault.local.m1xxos.tech`)
    kind: Rule
    services:
    - name: vault-ui
      kind: Service
      port: 8200
  tls:
    secretName: local-m1xxos-tech
