---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: "0.29.0"
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: vault
  releaseName: vault
  values:
    ui:
      enabled: true
    server:
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
          config: |
            cluster_name = "vault-integrated-storage"
            storage "raft" {
               path    = "/vault/data/"
            }

            listener "tcp" {
               address = "[::]:8200"
               cluster_address = "[::]:8201"
               tls_disable = "true"
            }
            service_registration "kubernetes" {}
