---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: assets/vault
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: vault
  releaseName: vault
  valuesFrom:
  - kind: ConfigMap
    name: vault-values
