---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: "0.28.1+yckms"
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: vault
  install:
    createNamespace: true
  targetNamespace: vault
  releaseName: vault
  valuesFrom:
  - kind: ConfigMap
    name: vault-values
