---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vault
  namespace: vault
spec:
  type: "oci"
  interval: 10m
  url: oci://cr.yandex/yc-marketplace/yandex-cloud/vault/chart/vault
