apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: capi-store
  namespace: proxmox-infrastructure-system
spec:
  provider:
    vault:
      server: "https://vault.local.m1xxos.online"
      path: "main"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "capi-reader"
          serviceAccountRef:
            name: "capi-reader"
