apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.labels }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        # volumeMounts:
        # - name: {{ .Values.name }}-config
        #   mountPath: "/config/qBittorrent/qBittorrent.conf"
        #   subPath: qBittorrent.conf

        resources:
          requests:
            memory: "200Mi" 
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
        
        ports:
        - containerPort: {{ .Values.service.httpPort }}
        - containerPort: {{ .Values.service.connectionPort }}
        - containerPort: {{ .Values.service.connectionPort }}
          protocol: UDP
        
      volumes:
      - name: {{ .Values.name }}-config
        configMap:
          name: {{ .Values.name }}-config
                
