apiVersion: v1
kind: Service
metadata:
  namespace: {{ values.namespace }}
  name: {{ include "qbittorent.fullname" . }}
  labels:
    {{ values.labels }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{ values.labels }}
