apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.name }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.10.0/24
  controlPlaneRef:
    kind: MicroK8sControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: {{ .Values.name }}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxCluster
    name: {{ .Values.name }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: {{ .Values.name }}
spec:
  # memory fix
  schedulerHints:
    memoryAdjustment: 0
  allowedNodes:
    - pve
  controlPlaneEndpoint:
    host: {{ .Values.network.host }}
    port: 6443
  dnsServers:
    - 1.1.1.1
    - 1.1.0.0
  ipv4Config:
    addresses:
      - {{ .Values.network.addresses }}
    gateway: {{ .Values.network.gateway }}
    prefix: {{ .Values.network.prefix }}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: MicroK8sControlPlane
metadata:
  name: {{ .Values.name }}-control-plane
spec:
  controlPlaneConfig:
    initConfiguration:
      joinTokenTTLInSecs: 900000
      addons:
        - dns
        # - cert-manager
        # - metrics-server
        # - metallb
    clusterConfiguration:
      portCompatibilityRemap: true
  machineTemplate:
    infrastructureTemplate:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: ProxmoxMachineTemplate
      name: {{ .Values.name }}-control-plane
  replicas: {{ .Values.controlPlane.replicas }}
  version: {{ .Values.version }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: {{ .Values.name }}-control-plane
spec:
  template:
    spec:
      disks:
        bootVolume:
          disk: {{ .Values.machineTemplate.disk }}
          sizeGb: {{ .Values.machineTemplate.sizeGb }}
      format: qcow2
      full: true
      memoryMiB: {{ .Values.machineTemplate.memoryMiB }}
      network:
        default:
          bridge: {{ .Values.machineTemplate.bridge }}
          model: virtio
      numCores: {{ .Values.machineTemplate.numCores }}
      numSockets: {{ .Values.machineTemplate.numSockets }}
      sourceNode: {{ .Values.machineTemplate.sourceNode }}
      templateID: {{ .Values.machineTemplate.templateID }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ .Values.name }}-workers
spec:
  clusterName: {{ .Values.name }}
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        node-role.kubernetes.io/node: ""
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: MicroK8sConfigTemplate
          name: {{ .Values.name }}-worker
      clusterName: {{ .Values.name }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        name: {{ .Values.name }}-worker
      version: {{ .Values.version }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: {{ .Values.name }}-worker
spec:
  template:
    spec:
      disks:
        bootVolume:
          disk: {{ .Values.machineTemplate.disk }}
          sizeGb: {{ .Values.machineTemplate.sizeGb }}
      format: qcow2
      full: true
      memoryMiB: {{ .Values.machineTemplate.memoryMiB }}
      network:
        default:
          bridge: {{ .Values.machineTemplate.bridge }}
          model: virtio
      numCores: {{ .Values.machineTemplate.numCores }}
      numSockets: {{ .Values.machineTemplate.numSockets }}
      sourceNode: {{ .Values.machineTemplate.sourceNode }}
      templateID: {{ .Values.machineTemplate.templateID }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: MicroK8sConfigTemplate
metadata:
  name: {{ .Values.name }}-worker
spec:
  template:
    spec:
      clusterConfiguration:
        portCompatibilityRemap: true
