apiVersion: operator.victoriametrics.com/v1
kind: VLSingle
metadata:
  name: main
spec:
  retentionPeriod: "3d"
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      memory: 256Mi
  storage:
    storageClassName: longhorn-single
    resources:
      requests:
        storage: 10Gi
  serviceSpec:
    metadata:
      annotations:
        service.cilium.io/global: "true"
    spec: {}
    useAsDefault: true
