{{- if .Values.ingress.enabled}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "arr-app.fullname" . }}
  labels:
    {{- include "arr-app.labels" . | nindent 4 }}
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - match: Host(`{{ .Values.ingress.hosts.app }}`)
    kind: Rule
    services:
    - name: {{ include "arr-app.fullname" . }}
      port: {{ .Values.service.port }}
      sticky:
        cookie: {}
  - match: Host(`{{ .Values.ingress.hosts.app }}`) && PathPrefix(`/metrics`)
    kind: Rule
    services:
    - name: {{ include "arr-app.fullname" . }}
      port: {{ .Values.metrics.port }}
      sticky:
        cookie: {}
{{- end }}
