version: '3.8'


services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  rancher:
    image: 'rancher/rancher:v2.9-head'
    privileged: true
    restart: unless-stopped
    volumes:
      - ./rancher:/var/lib/rancher
