- name: Proxy configuration
  hosts: groupnginx
  become: true
  vars:
    docker_users:
      - m1xxos
  # roles:
  #   - geerlingguy.docker
  tasks:
    - name: Create a nginx directory if it does not exist
      ansible.builtin.file:
        path: /etc/nginx-proxy/
        state: directory
        mode: '775'
    - name: Create a rancher directory if it does not exist
      ansible.builtin.file:
        path: /etc/nginx-proxy/rancher/
        state: directory
        mode: '775'
    - name: Copy docker compose config
      ansible.builtin.copy:
        src: docker-compose.yaml
        dest: /etc/nginx-proxy/docker-compose.yaml
        mode: '775'
    - name: Run nginx proxy docker-compose Up
      community.docker.docker_compose_v2:
        project_src: /etc/nginx-proxy/
