# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
    - echo "{{.GREETING}}"
    silent: true
  flux:
    cmds:
    - flux reconcile source git flux-system
    - flux reconcile kustomization flux-system
    - flux reconcile kustomization main-tenant
    - flux reconcile kustomization main-infra
    - flux reconcile kustomization main-configs
  new-cluster:
    desc: "Scaffold a new CAPI-managed Talos cluster in the repo"
    cmds:
    - ./scripts/new-cluster.sh

  add-kubeconfig:
    desc: "Fetch CA from CAPI secret and add OIDC context to kubeconfig. Usage: task add-kubeconfig CLUSTER=<name>"
    cmds:
    - ./scripts/add-kubeconfig.sh {{.CLUSTER}}

  add-sops:
    desc: "Copy sops-gpg secret from flux-system to a target namespace. Usage: task add-sops NAMESPACE=<ns>"
    cmds:
    - ./scripts/add-sops.sh {{.NAMESPACE}}

  tfplan:
    cmds:
    - terraform -chdir=terraform/0-infra/ plan
    - terraform -chdir=terraform/1-vault/ plan
    - terraform -chdir=terraform/2-authentik/ plan
