# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
    - echo "{{.GREETING}}"
    silent: true
  flux:
    cmds:
    - flux reconcile source git flux-system
    - flux reconcile kustomization flux-system
    - flux reconcile kustomization main-infra
    - flux reconcile kustomization flux-system-configs
    - flux reconcile kustomization gitlab-cluster-tenant -n gitlab-cluster
    - flux reconcile kustomization gitlab-cluster-system -n gitlab-cluster
  tfplan:
    cmds:
    - terraform -chdir=terraform/0-infra/ plan
    - terraform -chdir=terraform/1-vault/ plan
    - terraform -chdir=terraform/2-authentik/ plan
