# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
    - echo "{{.GREETING}}"
    silent: true
  flux:
    cmds:
    - flux reconcile source git flux-system
    - flux reconcile kustomization flux-system
    - flux reconcile kustomization main-tenant
    - flux reconcile kustomization main-infra
    - flux reconcile kustomization main-configs
  gitlab:
    cmds:
    - flux reconcile source git flux-system
    - flux reconcile kustomization gitlab-cluster-tenant -n gitlab-cluster
    - flux reconcile kustomization gitlab-cluster-critical -n gitlab-cluster
    - flux reconcile kustomization gitlab-cluster-infra -n gitlab-cluster
    - flux reconcile kustomization gitlab-cluster-configs -n gitlab-cluster
  new-cluster:
    desc: "Scaffold a new CAPI-managed Talos cluster in the repo"
    cmds:
    - ./scripts/new-cluster.sh
  tfplan:
    cmds:
    - terraform -chdir=terraform/0-infra/ plan
    - terraform -chdir=terraform/1-vault/ plan
    - terraform -chdir=terraform/2-authentik/ plan
  app:
    cmds:
    - flux reconcile source git flux-system
    - flux reconcile kustomization app-cluster-tenant -n app-cluster
    - flux reconcile kustomization app-cluster-critical -n app-cluster
    - flux reconcile kustomization app-cluster-infra -n app-cluster
    - flux reconcile kustomization app-cluster-configs -n app-cluster

