- name: LoadBalancer configuration
  hosts: grouphome
  become: true
  vars:
    docker_users:
      - m1xxos
  roles:
    - geerlingguy.docker
- name: Keepalived setup
  ansible.builtin.import_playbook: keepalived.yaml

- name: Haproxy setup
  ansible.builtin.import_playbook: haproxy-docker.yaml
