name: proxmox-dev
version: v1.28.9

network:
  host: 192.168.1.110
  addresses: 192.168.1.111-192.168.1.200
  gateway: 192.168.1.1
  prefix: 24

user:
  sshAuthorizedKeys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqNOWKBXOjOymiq1GDAfzGg26+O7uDHdie6t/IUfQc+nT3NTvx3n1bQYdW/koixKLSK8IdOInkwk5nyxUC7MzeZqlSQmjHkdGPoUKP6hIFmf0fNsBjY6E+gBtq7qeR+vi9MeLSoT0gtNI9hOI4CUMAquNoAxpoorJclQxgG2tSzAtaWe35gsn1opG4keIaEg1EnFBJzrSBcSB/G+/gegz+QVDpxy0iHmAHxCLD7/agxABVXb04RDUn2vCw7f77iaQSCsT22XkrpzACoBJtEja7LtmZTZQvitD+voi1uRxZMoQYoH+FAlKWvGNrCfQE2E8GPE6zUXR2geREd9Lgxcw5 harvester

controlPlane:
  replicas: 1
worker:
  replicas: 1

machineTemplate:
  disk: scsi0
  sizeGb: 20
  memoryMiB: 4096
  bridge: vmbr0
  numCores: 4
  numSockets: 1
  sourceNode: pve
  templateID: 105