---
apiVersion: operator.cluster.x-k8s.io/v1alpha
kind: InfrastructureProvider
metadata:
  name: proxmox
  namespace: proxmox-infrastructure-system
spec:
  version: v0.5.1
  configSecret:
    name: proxmox-variables
