---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: proxmox
  namespace: proxmox-infrastructure-system
spec:
  version: v0.5.2
  fetchConfig:
    url: https://github.com/isZumpo/cluster-api-provider-proxmox/releases/latest/infrastructure-components.yaml
  configSecret:
    name: proxmox-variables
