---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capi-operator
  namespace: capi-operator-system
spec:
  interval: 20m
  chart:
    spec:
      chart: cluster-api-operator
      version: 0.25.0
      sourceRef:
        kind: HelmRepository
        name: capi-operator
        namespace: flux-system
  install:
    createNamespace: true
    timeout: 90s
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  targetNamespace: capi-operator-system
  releaseName: capi-operator
  values:
    bootstrap:
      talos: {}
    controlPlane:
      talos: {}
    infrastructure:
      proxmox: {}
