---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capi-operator
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cluster-api-operator
      version: 0.21.0
      sourceRef:
        kind: HelmRepository
        name: capi-operator
        namespace: flux-system
  install:
    createNamespace: true
    timeout: 90s
  targetNamespace: capi-operator-system
  releaseName: capi-operator
  values:
    bootstrap: talos
    controlPlane: talos
    infrastructure: proxmox
