alertmanager:
  config:
  global:
    telegram_api_url: "https://api.telegram.org"
  route:
    receiver: telegram-alert
    group_by: ['alertname', 'cluster', 'service']
    repeat_interval: 1h
    routes:
      - matchers:
          - "severity = critical"
        receiver: telegram-alert
        continue: true
  receivers:
    - name: telegram-alert
      telegram_configs:
        - chat_id: 421268717
          bot_token: <BotToken>
          api_url: "https://api.telegram.org"
          send_resolved: true
          parse_mode: html
          template: |-
            {{ define "telegram.default" }}
            {{ range .Alerts }}
            {{ if eq .Status "firing"}}&#x1F525<b>{{ .Status | toUpper }}</b>&#x1F525{{ else }}&#x2705<b>{{ .Status | toUpper }}</b>&#x2705{{ end }}
            <b>{{ .Labels.alertname }}</b>
            {{- if .Labels.severity }}
            <b>Severity:</b> {{ .Labels.severity }}
            {{- end }}
            {{- if .Labels.cluster }}
            <b>Cluster:</b> {{ .Labels.cluster }}
            {{- end }}
            {{- if .Labels.service }}
            <b>Service:</b> {{ .Labels.service }}
            {{- end }}
            {{- if .Labels.instance}}
            <b>Instance:</b> {{ .Labels.instance }}
            {{- end }}
            <b>Description:</b> {{ .Annotations.description }}
            {{- end }}

prometheus:
  prometheusSpec:
      additionalScrapeConfigs:
        - job_name: 'kubernetes-pods'
          kubernetes_sd_configs:
            - role: pod
              selectors:
                - role: pod
                  label: "app=traefik"
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
              action: replace
              regex: ([^:]+)(?::\\d+)?;(\\d+)
              replacement: $1:$2
              target_label: __address__
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
              action: replace
              target_label: __scheme__
              regex: (https?)
