---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs
  namespace: seaweedfs
spec:
  interval: 30m
  chart:
    spec:
      chart: seaweedfs
      version: 4.0.412
      sourceRef:
        kind: HelmRepository
        name: seaweedfs
        namespace: seaweedfs
  values:
    s3:
      annotations:
        service.cilium.io/global: "true"
    master:
      data:
        type: "persistentVolumeClaim"
        size: "1Gi"
      logs:
        type: "emptyDir"
    filer:
      s3:
        enabled: true
        enableAuth: true
        existingConfigSecret: seaweedfs-s3-config
      data:
        type: "persistentVolumeClaim"
        size: "1Gi"
      logs:
        type: "emptyDir"
    volume:
      replicas: 2
      dataDirs:
      - name: data
        type: "persistentVolumeClaim"
        size: "3Gi"
        maxVolumes: 0 # If set to zero on non-windows OS, the limit will be auto configured. (default "7")
    admin:
      enabled: true
    cosi:
      enabled: true
