---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs
  namespace: seaweedfs
spec:
  interval: 30m
  postRenderers:
  - kustomize:
      patches:
      - target:
          kind: Service
          name: seaweedfs-s3
        patch: |
          - op: add
            path: /metadata/annotations/service.cilium.io~1global
            value: "true"
  chart:
    spec:
      chart: seaweedfs
      version: 4.0.412
      sourceRef:
        kind: HelmRepository
        name: seaweedfs
        namespace: seaweedfs
  values:
    master:
      data:
        type: "persistentVolumeClaim"
        size: "1Gi"
      logs:
        type: "emptyDir"
    filer:
      s3:
        enabled: true
        enableAuth: true
      enablePVC: true
      storage: 1Gi
      data:
        type: "persistentVolumeClaim"
        size: "1Gi"
      logs:
        type: "emptyDir"
    volume:
      dataDirs:
      - name: data
        type: "persistentVolumeClaim"
        size: "3Gi"
        maxVolumes: 0 # If set to zero on non-windows OS, the limit will be auto configured. (default "7")
    admin:
      enabled: true
    cosi:
      enabled: true
