apiVersion: homelab.m1xxos.online/v1alpha1
kind: Cluster
metadata:
  name: test
spec:
  controlPlane:
    replicas: 1
    vip: 192.168.1.175
  workers:
    replicas: 1
    ipRange: 192.168.1.181-192.168.1.190
  networking:
    podCidr: 10.169.0.0/16
    gateway: 192.168.1.1
    dnsName: test.m1xxos.online
    externalIp: 192.168.1.85
  cilium:
    id: 2
    clustermeshEndpoint: 192.168.1.86
  proxmox:
    node: plusha
    templateID: 110
  versions:
    kubernetes: v1.35.0
    talos: v1.12.2
