---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: tracing
spec:
  interval: 20m
  chart:
    spec:
      chart: tempo
      version: "1.24.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    persistence:
      enabled: "true"
      size: 5Gi
