---
apiVersion: v1
kind: Secret
metadata:
  name: cilium-clustermesh
  namespace: kube-system
stringData:
  main: |
    endpoints:
    - https://clustermesh-apiserver.kube-system.svc:2379
    trusted-ca-file: /var/lib/cilium/clustermesh/local-etcd-client-ca.crt
    key-file: /var/lib/cilium/clustermesh/local-etcd-client.key
    cert-file: /var/lib/cilium/clustermesh/local-etcd-client.crt
