apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: harbor-pg
  namespace: harbor
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: harbor-pg
  podMetricsEndpoints:
  - port: metrics
