apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- authentik-pod-scraper.yaml
- cnpg-auth-pod-scraper.yaml
- cnpg-monitoring.yaml
- longhorn-alert.yaml
- longhorn-service-scraper.yaml
- traefik-service-scrape.yaml
