apiVersion: v1
kind: Namespace
metadata:
  name: helm-guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
