apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- authentik/
- capi-operator-system/
- cloudnative-pg/
- dragonfly/
- harbor/
- monitoring/
- seaweedfs/
- vault/
- unified-controllers/
- kro/
