---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.9.7
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - jellyfin-config:/config
      - tvseries:/data/tvshows
      - movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped
  
  jellyseerr:
    image: fallenbagel/jellyseerr:1.9.2
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Moscow
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - jellyseerr-config:/app/config
    restart: unless-stopped
  
  radarr:
    image: lscr.io/linuxserver/radarr:5.8.3
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - radarr-config:/config
      - movies:/movies #optional
      - downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

volumes:
  jellyfin-config:
  jellyseerr-config:
  radarr-config:
  tvseries:
  movies:
  downloads: