version: '3.8'


services:
  proxy:
    image: 'jc21/nginx-proxy-manager:2.11.3'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - /etc/nginx-proxy/data:/data
      - /etc/nginx-proxy/letsencrypt:/etc/letsencrypt

