---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: talos-ccm
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/talos-cloud-controller-manager
      version: 0.5.2
      sourceRef:
        kind: HelmRepository
        name: talos-ccm
        namespace: flux-system
  targetNamespace: kube-system
  values:
    enabledControllers:
    - cloud-node
    - cloud-node-lifecycle
    - node-csr-approval
