apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-vault
  namespace: authentik
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: authentik-vault
    kind: SecretStore
  target:
    name: authentik-key
  data:
  - secretKey: secret_key
    remoteRef:
      key: authentik
      property: secret_key
