---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 20m
  chart:
    spec:
      chart: authentik
      version: 2026.2.0
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: authentik
  valuesFrom:
  - kind: ConfigMap
    name: authentik-values
    valuesKey: values.yaml
