---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2025.10.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: authentik
  valuesFrom:
    - kind: ConfigMap
      name: authentik-values
      valuesKey: values.yaml
