apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: authentik-vault
  namespace: authentik
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "authentik"
          key: "token"
