apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault-agent-injector
  name: vault-agent-injector-cfg-authentik
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNTVENDQWU2Z0F3SUJBZ0lVV1VBSC84aWY2YnN5Mlp6MitNbWdGMFdiZlI4d0NnWUlLb1pJemowRUF3SXcKR2pFWU1CWUdBMVVFQXhNUFFXZGxiblFnU1c1cVpXTjBJRU5CTUI0WERUSTFNVEl4TnpFNU1EZ3dOVm9YRFRNMQpNVEl4TlRFNU1Ea3dOVm93R2pFWU1CWUdBMVVFQXhNUFFXZGxiblFnU1c1cVpXTjBJRU5CTUZrd0V3WUhLb1pJCnpqMENBUVlJS29aSXpqMERBUWNEUWdBRVpVSTZRZGp6Nk4wOHdyeDdTbTF4YnppeGVjK0sybHVXc2JLK1N2WGQKZEhsaHl2bHpvakdWNkhtZVlSV3hwSmNaUkJZaS9UZnNsYkRyNm41WFJvMEl1cU9DQVJBd2dnRU1NQTRHQTFVZApEd0VCL3dRRUF3SUNoREFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRBUEJnTlZIUk1CQWY4RUJUQURBUUgvCk1HZ0dBMVVkRGdSaEJGOWxZanBrWXpvNU5qbzFZam95WmpwaFpEcGhOem8yWVRveE1qbzRPVHBsWmpwbE1EbzAKTkRvMk9UcGxaVHBpTXpvd1lUcGhNanBpWlRvMlpEcGtOem94TXpveFlUbzVOam95TnpveE5Eb3pPVHBrWXpwagpZem8xWlRvM01UbzJOekJxQmdOVkhTTUVZekJoZ0Y5bFlqcGtZem81TmpvMVlqb3laanBoWkRwaE56bzJZVG94Ck1qbzRPVHBsWmpwbE1EbzBORG8yT1RwbFpUcGlNem93WVRwaE1qcGlaVG8yWkRwa056b3hNem94WVRvNU5qb3kKTnpveE5Eb3pPVHBrWXpwall6bzFaVG8zTVRvMk56QUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUE4SW16d3J4dgoyVmQwUS9CNEtLckJQeTFlV3hQbDVLSEhBWHV1NE5Ld0VEY0NJUURuVCtaU0pqa3FjNGIwLzF0WW9uNFdpak94CnZhWkJIQnJycXhJMlZkMzZvZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNTRENDQWU2Z0F3SUJBZ0lVTjZyOTRPUy9EOXp5bUhhWERPR0FxbzRsWlRFd0NnWUlLb1pJemowRUF3SXcKR2pFWU1CWUdBMVVFQXhNUFFXZGxiblFnU1c1cVpXTjBJRU5CTUI0WERUSTFNVEl4T0RFM05URTFOMW9YRFRNMQpNVEl4TmpFM05USTFOMW93R2pFWU1CWUdBMVVFQXhNUFFXZGxiblFnU1c1cVpXTjBJRU5CTUZrd0V3WUhLb1pJCnpqMENBUVlJS29aSXpqMERBUWNEUWdBRS9aL3ZSNXBnRGw0bmRjMXRCSVJNQ1JsRzYxcUJvOVVrYy9FR1IvVlkKcWdhZUY2YlV3ekNFbVR0L1Q0Z09YVVR3QkZ2RGVKeGgyN0hBSTRKQ0dCLzJmNk9DQVJBd2dnRU1NQTRHQTFVZApEd0VCL3dRRUF3SUNoREFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRBUEJnTlZIUk1CQWY4RUJUQURBUUgvCk1HZ0dBMVVkRGdSaEJGOWhOVG80TlRwa01Ub3hNRG81Wmpvek1Ub3hZVG8xTWpwaVl6b3hPVG93TVRvME9Ub3oKWXpvek16cGlOVHBrWVRwak5qb3lNVG8yTURvMU5qcG1aVHBoWVRvME1qbzFZenBtT0RveU16bzBZVHBpWXpwagpNenBpTVRvM09UbzBOVEJxQmdOVkhTTUVZekJoZ0Y5aE5UbzROVHBrTVRveE1EbzVaam96TVRveFlUbzFNanBpCll6b3hPVG93TVRvME9Ub3pZem96TXpwaU5UcGtZVHBqTmpveU1UbzJNRG8xTmpwbVpUcGhZVG8wTWpvMVl6cG0KT0RveU16bzBZVHBpWXpwak16cGlNVG8zT1RvME5UQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQUhXSmNsL29RRApTNDk2akNSNkMrc21IcHRod1I3dkFHdjhiaXpBVWR4OWR3SWhBTzJNRG82T2tjUFpVYmQxZjdZeEtmL0hvS014Cm05akhiYmhoM1RWTzEyM0gKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: vault-agent-injector-svc
      namespace: vault
      path: /mutate
      port: 443
  failurePolicy: Ignore
  matchPolicy: Exact
  name: vault.hashicorp.com
  namespaceSelector: {}
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: In
      values:
      - authentik
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 30
