services:
  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    networks:
      - monitoring_default
      - proxynet
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  
  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring_default
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    
  alert-manager:
    image: prom/alertmanager:v0.27.0
    container_name: alert-manager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yaml'
    networks:
      - monitoring_default
    ports:
      - 9093:9093
    restart: unless-stopped
    volumes:
      - ./alertmanager:/etc/alertmanager
      - alert_data:/alertmanager

  grafana:
    image: grafana/grafana:11.1.1
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - monitoring_default
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - dashboards:/etc/grafana/provisioning/dashboards/

volumes:
  prom_data:
  alert_data:
  dashboards:
networks:
  proxynet:
    name: home-stuff_default
    external: true
  monitoring_default:
