services:
  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    networks:
      - monitoring_default
      - proxynet
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - monitoring_default
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

volumes:
  prom_data:
networks:
  proxynet:
    name: home-stuff_default
    external: true
  monitoring_default:
