apiVersion: v1
kind: Secret
metadata:
  name: kms-creds
  namespace: {{ .Release.Namespace | quote }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  "credentials.json": {{ .Values.yandexKmsAuthJson | b64enc }}
