apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: example-inline
  namespace: crossplane-system
  annotations:
    crossplane.io/external-name: coolbucket
spec:
  forProvider:
    initArgs:
      - -upgrade=true
    source: Inline
    module: |
      resource "proxmox_vm_qemu" "test_vm" {
        name        = "test"
        vmid        = 1228
        target_node = "pve"
        desc        = "testtest"
        qemu_os     = "l26"

        cores       = 4
        memory      = 4096
        agent       = 1

        clone = "ubuntu-server-noble"

        disks {
          virtio {
            virtio0 {
              disk {
                storage = "pve-nvme"
                size    = 20
              }
            }
          }
          ide {
            ide2 {
              cdrom {
                passthrough = false
              }
            }
            ide3 {
              cloudinit {
                storage  = "local-lvm"
              }
            }
          }
        }
        os_type                 = "cloud-init"

        network {
          bridge = "vmbr0"
          model  = "virtio"
        }

        ipconfig0 = "ip=dhcp"
      }
  writeConnectionSecretToRef:
    namespace: default
    name: terraform-workspace-example-inline