apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-ippool
spec:
  blocks:
  - start: 192.168.1.85
    stop: 192.168.1.85
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: clustermesh-pool
spec:
  blocks:
  - start: 192.168.1.86
    stop: 192.168.1.86
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: clustermesh-apiserver
