apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pulsar
  namespace: pulsar
spec:
  releaseName: pulsar
  chart:
    spec:
      chart: pulsar
      sourceRef:
        kind: HelmRepository
        name: pulsar
        namespace: flux-system
  interval: 10m
  values:
    victoria-metrics-k8s-stack:
      enabled: false
    bookkeeper:
      volumes:
        journal:
         size: 1Gi
        ledgers:
          size: 2Gi
    zookeeper:
      volumes:
        data:
          size: 2Gi
        datalog:
          size: 2Gi
    
