apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pulsar
  namespace: pulsar
spec:
  releaseName: pulsar
  chart:
    spec:
      chart: pulsar
      sourceRef:
        kind: HelmRepository
        name: pulsar
        namespace: flux-system
  interval: 10m
