{{- if .Values.prometheus.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hotrod.fullname" . }}
  labels:
    {{- include "hotrod.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hotrod.selectorLabels" . | default .Values.prometheus.service.annotations | nindent 6 }}
  endpoints:
  - port: {{ .Values.service.port }}
{{- end -}}