- name: Docker registry change
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Create k3s directory
      ansible.builtin.file:
        path: /etc/rancher/k3s/
        state: directory
    - name: Create registries file
      ansible.builtin.file:
        path: /etc/rancher/k3s/registries.yaml
        state: touch
    - name: Add docker registry mirror
      ansible.builtin.copy:
        src: ../registries.yaml
        dest: /etc/rancher/k3s/registries.yaml
