apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: node-exporter
  targetNamespace: monitoring
  values:
    imagePullSecrets:
    - name: dhi-registry
    prometheus:
      monitor:
        enabled: true
