apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: kube-state-metrics
  targetNamespace: monitoring
  values:
    fullnameOverride: gl-kube-state-metrics
    imagePullSecrets:
    - name: dhi-registry
    prometheus:
      monitor:
        enabled: true
        jobLabel: "gl-cluster-state-metrics"
