---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vmagent
spec:
  releaseName: vmagent
  interval: 5m
  chart:
    spec:
      chart: victoria-metrics-agent
      version: 0.29.0
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: flux-system
  targetNamespace: monitoring
  values:
    remoteWrite:
    - url: http://metrics.local.m1xxos.tech/api/v1/write
