---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm-operator
spec:
  releaseName: vm-operator
  interval: 20m
  chart:
    spec:
      chart: victoria-metrics-operator
      version: 0.59.0
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: flux-system
  targetNamespace: monitoring
