apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
      version: 0.24.0
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: cnpg-system
