apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-cluster-tenant
  namespace: app-cluster
spec:
  dependsOn:
  - name: flux-system
    namespace: flux-system
  interval: 10m0s
  path: ./clusters/app-tenant
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  kubeConfig:
    secretRef:
      name: proxmox-app-kubeconfig
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute:
      CLUSTER_NAME: app-cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-cluster-critical
  namespace: app-cluster
spec:
  dependsOn:
  - name: app-cluster-tenant
  targetNamespace: app-cluster
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  path: ./infra/critical
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      CILIUM_CLUSTER_NAME: app
      CILIUM_CLUSTER_ID: "3"
      CILIUM_CLUSTERMESH_ENDPOINT: "192.168.1.22"
  patches:
  - target:
      kind: HelmRelease
    patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          secretRef:
            name: proxmox-app-kubeconfig
      - op: add
        path: /spec/serviceAccountName
        value: flux-cluster-admin
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-cluster-infra
  namespace: app-cluster
spec:
  dependsOn:
  - name: app-cluster-tenant
  - name: app-cluster-critical
  targetNamespace: app-cluster
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  path: ./clusters/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
  - target:
      kind: HelmRelease
    patch: |
      - op: add
        path: /spec/kubeConfig
        value:
          secretRef:
            name: proxmox-app-kubeconfig
      - op: add
        path: /spec/serviceAccountName
        value: flux-cluster-admin
      - op: replace
        path: /metadata/namespace
        value: app-cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-cluster-configs
  namespace: app-cluster
spec:
  dependsOn:
  - name: app-cluster-tenant
  - name: app-cluster-critical
  interval: 10m0s
  path: ./clusters/app-configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  kubeConfig:
    secretRef:
      name: proxmox-app-kubeconfig
  postBuild:
    substitute:
      DNS_NAME: app.m1xxos.tech
      CILIUM_CLUSTER_NAME: app
      CILIUM_CLUSTERMESH_ENDPOINT: "192.168.1.22"
