apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- authentik.yaml
- capi-operator-system.yaml
- cnpg-system.yaml
- dragonfly-operator-system.yaml
- harbor.yaml
- monitoring.yaml
- seaweedfs.yaml
- vault.yaml
- tracing-ns.yaml
- kro.yaml
- test-cluster.yaml
