---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cilium-clustermesh
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-general
    kind: ClusterSecretStore
  target:
    name: cilium-clustermesh
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: clustermesh/gitlab
