# Default values for qbittorent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: qbittorent
labels: qbittorent

namespace: torrent

image:
  name: wernight/qbittorrent
  tag: "latest"

service:
  httpPort: 8080
  connectionPort: 6881

ingress:
  hostname: torrent.local.m1xxos.tech

storageClass: nfs-client
