version: '3.8'

services:
  haproxy:
    image: haproxy:3.0
    ports:
      - 80:80
      - 443:443
      - 6443:6443
      - 9291:9291
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    restart: unless-stopped
    volumes: 
      - /etc/haproxy:/usr/local/etc/haproxy/haproxy.cfg:ro