apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: main-m1xxos-me
  namespace: cert-manager
spec:
  secretName: main-m1xxos-me
  dnsNames:
  - "main.m1xxos.me"
  - "*.main.m1xxos.me"
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
