apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arr-stack

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- volume.yaml

labels:
- includeSelectors: true
  pairs:
    app: sonarr

images:
- name: lscr.io/linuxserver/sonarr
  newTag: 4.0.15
- name: ghcr.io/onedr0p/exportarr
  newTag: v2.2

secretGenerator:
- name: api-key
  envs:
  - .env.secret
