apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arr-stack

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- volume.yaml

labels:
- includeSelectors: true
  pairs:
    app: sonarr

images:
- name: lscr.io/linuxserver/sonarr
  newTag: 4.0.8

secretGenerator:
- name: sonarr-api-key
  envs:
  - .env.secret
