apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: my-ldap-auth
    namespace: default
spec:
    plugin:
        ldapAuth:
            Attribute: uid
            BaseDn: dc=example,dc=org
            Enabled: "true"
            LogLevel: DEBUG
            Port: "389"
            Url: ldap://192.168.1.228

