apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: metrics
  namespace: dev
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`metrics.local.m1xxos.me`)
      kind: Rule
      services:
        - name: prometheus@internal
          kind: TraefikService
  tls:
   secretName: local-m1xxos-me
