apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: test
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`testraefik.local.m1xxos.me`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: my-ldap-auth

  tls:
   secretName: local-m1xxos-me


