apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      name: traefik
      tag: 2.10.7
    deployment:
      replicas: 1
    ports:
      web:
        redirectTo:
          port: websecure
    additionalVolumes:
      - name: plugins
        emptyDir:
          sizeLimit: 500Mi
    volumes:
      - name: plugins
        mountPath: /usr/local/bin/plugins-storage
        readOnly: false
