apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      name: traefik
      tag: 2.10.5
    deployment:
      replicas: 1
    ports:
      web:
        redirectTo:
          port: websecure