apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-pg-secret
  namespace: harbor
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-general
    kind: ClusterSecretStore
  target:
    name: harbor-pg-app
    template:
      engineVersion: v2
      data:
        username: harbor
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: harbor/postgres
      property: password
