apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: harbor-dragonfly
  namespace: harbor
spec:
  replicas: 1
  resources:
    requests:
      cpu: 60m
      memory: 128Mi
    limits:
      memory: 256Mi
