apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core-secret
  namespace: harbor
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-general
    kind: ClusterSecretStore
  target:
    name: harbor-core-secret
  data:
  - secretKey: secretKey
    remoteRef:
      key: harbor/core
      property: secretKey
