apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-secret
  namespace: harbor
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: harbor-store
  target:
    name: harbor-admin-secret
  data:
  - secretKey: HARBOR_ADMIN_PASSWORD
    remoteRef:
      key: harbor/admin
      property: password
