apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-redis-secret
  namespace: harbor
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-general
    kind: ClusterSecretStore
  target:
    name: harbor-redis
  data:
  - secretKey: password
    remoteRef:
      key: harbor/redis
      property: password
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: harbor/redis
      property: password
