apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: harbor-dragonfly
  namespace: harbor
spec:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 400Mi
    limits:
      cpu: 600m
      memory: 750Mi
