apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- harbor-route.yaml
- harbor-admin-secret.yaml
- harbor-core-secret.yaml
- harbor-pg-secret.yaml
- harbor-pg-cluster.yaml
- harbor-redis-secret.yaml
- harbor-dragonfly.yaml
