apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: '32.0.0'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 10m
  valuesFrom:
  - kind: ConfigMap
    name: traefik-values
