apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik
  namespace: authentik
spec:
  instances: 2
  storage:
    size: 1Gi
  bootstrap:
    recovery:
      source: origin
      volumeSnapshots:
        storage:
          name: authentik-2
          kind: PersistentVolumeClaim
