apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: authentik-store
  data:
  - secretKey: secret-key
    remoteRef:
      key: authentik/secret-key
      property: secret-key
