releases:
- name: prom-norbac-ubuntu
  namespace: arr-test
  chart: ../arr-app
  set:
  - name: nameOverride
    value: "sonarr"
  - name: image.repository
    value: lscr.io/linuxserver/sonarr
  - name: image.tag
    value: "4.0.9"
  - name: metrics.type
    value: "sonarr"
  - name: service.port
    value: 8989
