apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dragonfly-gl
  namespace: gitlab
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-general
    kind: ClusterSecretStore
  data:
  - secretKey: password
    remoteRef:
      key: dragonfly-gl-password
      property: password
