apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-object-storage
  namespace: gitlab
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-general
    kind: ClusterSecretStore
  target:
    name: gitlab-object-storage
    template:
      engineVersion: v2
      data:
        config: |
          provider: AWS
          region: {{ default "us-east-1" .bucket_region }}
          aws_access_key_id: {{ .aws_access_key_id }}
          aws_secret_access_key: {{ .aws_secret_access_key }}
          endpoint: "http://seaweedfs-s3.seaweedfs.svc:8333"
          path_style: true
        s3cmd: |
          [default]
          access_key = {{ .aws_access_key_id }}
          secret_key = {{ .aws_secret_access_key }}
          host_base = seaweedfs-s3.seaweedfs.svc:8333
          host_bucket = seaweedfs-s3.seaweedfs.svc:8333/%(bucket)
          bucket_location = {{ default "us-east-1" .bucket_region }}
          use_https = False
          signature_v2 = False
  data:
  - secretKey: aws_access_key_id
    remoteRef:
      key: gitlab-object-storage
      property: aws_access_key_id
  - secretKey: aws_secret_access_key
    remoteRef:
      key: gitlab-object-storage
      property: aws_secret_access_key
  - secretKey: bucket_region
    remoteRef:
      key: gitlab-object-storage
      property: bucket_region
