---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: gitlab-rails-db-push
  namespace: gitlab-cluster
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
  - name: vault-general
    kind: ClusterSecretStore
  selector:
    secret:
      name: gitlab-rails-db-app
  template:
    data:
      password: '{{ index . "password" | toString }}'
  data:
  - conversionStrategy: None
    match:
      remoteRef:
        remoteKey: gitlab-rails-db-password
