---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-reader
  namespace: gitlab
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gitlab-store
  namespace: gitlab
spec:
  provider:
    vault:
      server: "https://vault.local.m1xxos.tech"
      path: "main"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "gitlab-reader"
          serviceAccountRef:
            name: "gitlab-reader"
