apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: clusters.homelab.m1xxos.online
spec:
  schema:
    apiVersion: v1alpha1
    kind: Cluster
    group: homelab.m1xxos.online
    scope: Namespaced
    spec:
      controlPlane:
        vip: string | required=true
        replicas: integer | default=1 minimum=1
        cpu: integer | default=4
        ramMiB: integer | default=4096
        diskGiB: integer | default=30
      workers:
        replicas: integer | default=2 minimum=1
        cpu: integer | default=4
        ramMiB: integer | default=6144
        diskGiB: integer | default=30
        ipRange: string | required=true
      networking:
        podCidr: string | default="10.169.0.0/16"
        gateway: string | default="192.168.1.1"
      proxmox:
        node: string | default="plusha"
        templateID: integer | default=110
      versions:
        kubernetes: string | default="v1.35.0"
        talos: string | default="v1.12.2"
    status:
      controlPlaneEndpoint: $${schema.spec.controlPlane.vip}
      kubernetesVersion: $${talosControlPlane.status.version}
      phase: $${capiCluster.status.phase}
      controlPlaneReplicas: $${capiCluster.status.controlPlane.replicas}
      controlPlaneAvailableReplicas: $${capiCluster.status.controlPlane.availableReplicas}
      workerReplicas: $${capiCluster.status.workers.replicas}
      workerReadyReplicas: $${capiCluster.status.workers.readyReplicas}
  resources:
  - id: clusterNamespace
    template:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: $${schema.metadata.name}-cluster
  - id: proxmoxCluster
    template:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
      kind: ProxmoxCluster
      metadata:
        name: proxmox-$${schema.metadata.name}
        namespace: $${clusterNamespace.metadata.name}
      spec:
        schedulerHints:
          memoryAdjustment: 0
        allowedNodes:
        - $${schema.spec.proxmox.node}
        controlPlaneEndpoint:
          host: $${schema.spec.controlPlane.vip}
          port: 6443
        dnsServers:
        - 1.1.1.1
        - 1.1.0.0
        ipv4Config:
          addresses:
          - $${schema.spec.workers.ipRange}
          gateway: $${schema.spec.networking.gateway}
          prefix: 24
          metric: 100
  - id: controlPlaneMachineTemplate
    template:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
      kind: ProxmoxMachineTemplate
      metadata:
        name: proxmox-$${schema.metadata.name}-control-plane
        namespace: $${clusterNamespace.metadata.name}
      spec:
        template:
          spec:
            disks:
              bootVolume:
                disk: scsi0
                sizeGb: $${schema.spec.controlPlane.diskGiB}
            format: qcow2
            full: true
            memoryMiB: $${schema.spec.controlPlane.ramMiB}
            network:
              networkDevices:
              - name: net0
                bridge: vmbr0
                model: virtio
            numCores: $${schema.spec.controlPlane.cpu}
            numSockets: 1
            sourceNode: $${schema.spec.proxmox.node}
            templateID: $${schema.spec.proxmox.templateID}
            checks:
              skipCloudInitStatus: true
            metadataSettings:
              providerIDInjection: true
  - id: workerConfigTemplate
    template:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
      kind: TalosConfigTemplate
      metadata:
        name: proxmox-$${schema.metadata.name}-worker
        namespace: $${clusterNamespace.metadata.name}
      spec:
        template:
          spec:
            generateType: worker
            talosVersion: $${schema.spec.versions.talos}
            strategicPatches:
            - |
              machine:
                install:
                  disk: /dev/sda
            - |
              machine:
                kubelet:
                  extraArgs:
                    cloud-provider: external
                    rotate-server-certificates: "true"
  - id: workerMachineTemplate
    template:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
      kind: ProxmoxMachineTemplate
      metadata:
        name: proxmox-$${schema.metadata.name}-worker
        namespace: $${clusterNamespace.metadata.name}
      spec:
        template:
          spec:
            disks:
              bootVolume:
                disk: scsi0
                sizeGb: $${schema.spec.workers.diskGiB}
            format: qcow2
            full: true
            memoryMiB: $${schema.spec.workers.ramMiB}
            network:
              networkDevices:
              - name: net0
                bridge: vmbr0
                model: virtio
            numCores: $${schema.spec.workers.cpu}
            numSockets: 1
            sourceNode: $${schema.spec.proxmox.node}
            templateID: $${schema.spec.proxmox.templateID}
            checks:
              skipCloudInitStatus: true
            metadataSettings:
              providerIDInjection: true
  - id: talosControlPlane
    template:
      apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
      kind: TalosControlPlane
      metadata:
        name: proxmox-$${schema.metadata.name}-control-plane
        namespace: $${clusterNamespace.metadata.name}
      spec:
        version: $${schema.spec.versions.kubernetes}
        replicas: $${schema.spec.controlPlane.replicas}
        infrastructureTemplate:
          kind: ProxmoxMachineTemplate
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
          name: $${controlPlaneMachineTemplate.metadata.name}
          namespace: $${clusterNamespace.metadata.name}
        controlPlaneConfig:
          controlplane:
            generateType: controlplane
            talosVersion: $${schema.spec.versions.talos}
            strategicPatches:
            - |
              machine:
                install:
                  disk: /dev/sda
                  extraKernelArgs:
                    - net.ifnames=0
                network:
                  interfaces:
                    - interface: eth0
                      dhcp: false
                      vip:
                        ip: $${schema.spec.controlPlane.vip}
                kubelet:
                  extraArgs:
                    rotate-server-certificates: "true"
                    cloud-provider: external
                features:
                  kubernetesTalosAPIAccess:
                    enabled: true
                    allowedRoles:
                      - os:reader
                    allowedKubernetesNamespaces:
                      - kube-system
            - |
              cluster:
                network:
                  cni:
                    name: none
                proxy:
                  disabled: true
                apiServer:
                  extraArgs:
                    oidc-issuer-url: "https://authentik.local.m1xxos.online/application/o/k8s/"
                    oidc-client-id: "k8s"
                    oidc-username-claim: name
                    oidc-groups-claim: groups
                    oidc-signing-algs: "ES256,RS256"
  - id: capiCluster
    template:
      apiVersion: cluster.x-k8s.io/v1beta2
      kind: Cluster
      metadata:
        name: proxmox-$${schema.metadata.name}
        namespace: $${clusterNamespace.metadata.name}
      spec:
        clusterNetwork:
          pods:
            cidrBlocks:
            - $${schema.spec.networking.podCidr}
        controlPlaneRef:
          apiGroup: controlplane.cluster.x-k8s.io
          kind: TalosControlPlane
          name: $${talosControlPlane.metadata.name}
        infrastructureRef:
          apiGroup: infrastructure.cluster.x-k8s.io
          kind: ProxmoxCluster
          name: $${proxmoxCluster.metadata.name}
  - id: workerMachineDeployment
    template:
      apiVersion: cluster.x-k8s.io/v1beta2
      kind: MachineDeployment
      metadata:
        name: proxmox-$${schema.metadata.name}-workers
        namespace: $${clusterNamespace.metadata.name}
      spec:
        clusterName: $${capiCluster.metadata.name}
        replicas: $${schema.spec.workers.replicas}
        selector:
          matchLabels:
            cluster.x-k8s.io/cluster-name: $${capiCluster.metadata.name}
        template:
          metadata:
            labels:
              node-role.kubernetes.io/node: "worker"
              cluster.x-k8s.io/cluster-name: $${capiCluster.metadata.name}
          spec:
            bootstrap:
              configRef:
                apiGroup: bootstrap.cluster.x-k8s.io
                kind: TalosConfigTemplate
                name: $${workerConfigTemplate.metadata.name}
            clusterName: $${capiCluster.metadata.name}
            infrastructureRef:
              apiGroup: infrastructure.cluster.x-k8s.io
              kind: ProxmoxMachineTemplate
              name: $${workerMachineTemplate.metadata.name}
            version: $${schema.spec.versions.kubernetes}
