- name: LoadBalancer configuration
  hosts: terraform-k3s-vm
  vars:
    docker_users:
      - m1xxos
    
  roles:
    - geerlingguy.docker
- name: Keepalived setup
  ansible.builtin.import_playbook: keepalived.yaml 

- name: haproxy setup
  ansible.builtin.import_playbook: haproxy-docker.yaml 
