apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: traefik
    server: {{ .Values.spec.destination.devServer }}
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 30.0.0
    helm:
      valuesObject:
        logs:
          general:
            level: DEBUG
          access:
            enable: true
    #     ports:
    #     web:
    #         redirectTo:
    #         port: websecure


  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
