apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitlab
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - chart: gitlab-runner
      repoURL: https://charts.gitlab.io
      targetRevision: 0.66.0
      helm:
        valueFiles:
          - $values/kuber/gtilab-runner/values.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
