---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: omnivore
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: omnivore
  releaseName: omnivore
  valuesFrom:
  - kind: ConfigMap
    name: omnivore-values
