---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.142.0"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: otel-values
    valuesKey: values.yaml
