---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: "0.29.0"
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: vault
  values:
    server:
      ha:
        enabled: true
        replicas: 3
