---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm-stack
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.55.1
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: monitoring
  valuesFrom:
  - kind: ConfigMap
    name: vm-values
    valuesKey: values.yaml
