---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://cr.yandex/yc-marketplace/yandex-cloud/vault/chart/vault
