---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm-stack
  namespace: monitoring
spec:
  interval: 20m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.72.2
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: flux-system
  targetNamespace: monitoring
  valuesFrom:
  - kind: ConfigMap
    name: vm-values
    valuesKey: values.yaml
