apiVersion: v1
kind: Service
metadata:
  annotations:
    service.cilium.io/global: "true"
  name: dragonfly-gl
  namespace: gitlab-cluster
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  type: ClusterIP
