apiVersion: v1
kind: Service
metadata:
  name: gitlab-rails-db-global-rw
  namespace: gitlab
  annotations:
    service.cilium.io/global: "true"
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  type: ClusterIP
