---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 20m
  chart:
    spec:
      chart: cilium
      version: 1.18.6
      sourceRef:
        kind: HelmRepository
        name: cilium
  install:
    disableWait: true
  upgrade:
    disableWait: true
  targetNamespace: kube-system
  valuesFrom:
  - kind: ConfigMap
    name: cilium-values
    valuesKey: values.yaml
