apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - match: Host(`longhorn.local.m1xxos.tech`)
    kind: Rule
    services:
    - name: longhorn-frontend
      kind: Service
      port: 80
  tls:
    secretName: local-m1xxos-tech
