apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-resource
  namespace: longhorn-system
data:
  default-resource.yaml: |
    "backup-target": "nfs://192.168.1.138:/mnt/main/lh-backup"
    "backupstore-poll-interval": "300"
