apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-delete
  namespace: longhorn-system
spec:
  cron: "30 */3 * * *"
  task: "snapshot-delete"
  groups:
  - default
  retain: 1
  concurrency: 2
