apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: system-backup
  namespace: longhorn-system
spec:
  task: system-backup
  cron: '30 */6 * * *'
  retain: 2
  parameters:
    volume-backup-policy: disabled
