apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: full-trim
  namespace: longhorn-system
spec:
  cron: "0 */3 * * *"
  task: "filesystem-trim"
  groups:
  - default
  retain: 1
  concurrency: 2
