---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-values
  namespace: monitoring
  labels:
    reconcile.fluxcd.io/watch: Enabled
data:
  values.yaml: |
    nameOverride: "vm"
    fullnameOverride: "vm"
    vmagent:
      route:
        enabled: true
        hostnames:
        - vmagent.local.m1xxos.online
        parentRefs:
        - name: traefik-gateway
          namespace: traefik
    vmsingle:
      spec:
        retentionPeriod: "1d"
        extraArgs:
          opentelemetry.usePrometheusNaming: "true"
        storage:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 5Gi
        serviceSpec:
          metadata:
            annotations:
              service.cilium.io/global: "true"
          spec:
            type: ClusterIP
          useAsDefault: true
      route:
        enabled: false
    prometheus-node-exporter:
      enabled: true
    kube-state-metrics:
      enabled: true
    grafana:
      enabled: false
    kubeScheduler:
      vmScrape:
        spec:
          endpoints:
          - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
            port: http-metrics
            scheme: https
            tlsConfig:
              caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecureSkipVerify: true
    kubeControllerManager:
      vmScrape:
        spec:
          endpoints:
          - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
            port: http-metrics
            scheme: https
            tlsConfig:
              caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              serverName: kubernetes
              insecureSkipVerify: true
