apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr
        env:
        - name: "TZ"
          value: "Europe/Moscow"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - name: radarr-config
          mountPath: /config
        ports:
        - containerPort: 7878
      initContainers:
      - name: metrics
        image: ghcr.io/onedr0p/exportarr:v2.0
        restartPolicy: Always
        args: ["radarr"]
        env:
        - name: "PORT"
          value: "9708"
        - name: "URL"
          value: "http://radarr:7878"
        - name: "APIKEY"
          valueFrom:
            secretKeyRef:
              name: api-key
              key: APIKEY
        ports:
        - containerPort: 9708
      volumes:
      - name: radarr-config
        persistentVolumeClaim:
          claimName: radarr-config-pvc
