apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arr-stack

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- volume.yaml

labels:
- includeSelectors: true
  pairs:
    app: radarr

images:
- name: lscr.io/linuxserver/radarr
  newTag: 5.26.2
- name: ghcr.io/onedr0p/exportarr
  newTag: v2.2

secretGenerator:
- name: api-key
  envs:
  - .env.secret
configMapGenerator:
- name: vpn-config
  files:
  - VPN-2500.ovpn
