apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arr-stack

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- volume.yaml

labels:
- includeSelectors: true
  pairs:
    app: radarr

images:
- name: lscr.io/linuxserver/radarr
  newTag: 5.8.3

secretGenerator:
- name: api-key
  envs:
  - .env.secret
