apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-cluster
  namespace: redis
spec:
  releaseName: redis-cluster
  chart:
    spec:
      chart: redis-cluster
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
        namespace: flux-system
  interval: 10m
  install:
    createNamespace: true
  values:
    persistence:
      size: 2Gi
